version: "3"

tasks:
  fmt:
    desc: format all code
    cmds:
      - go mod tidy
      - gci write -s standard -s default -s "prefix(github.com/utkuozdemir/sifre)" .
      - gofumpt -w -l .

  lint:
    desc: Lint the code with golangci-lint
    cmds:
      - go mod tidy && git diff --no-patch --exit-code go.mod go.sum
      - golangci-lint run ./...

  release:
    desc: Create a new tag
    vars:
      NEXT:
        sh: svu n
    cmds:
      - git tag {{.NEXT}}
      - echo {{.NEXT}}
      - git push origin {{.NEXT}}
