---
name: Build
on:
  push:
    branches:
      - master
      - renovate/**
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "renovate.json"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "renovate.json"

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
      - name: Install Go
        uses: actions/setup-go@v3.5.0
        with:
          # renovate: go
          go-version: 1.19.4
      - name: Install richgo
        # renovate: depName=kyoh86/richgo
        run: go install github.com/kyoh86/richgo@v0.3.11
      - name: Ensure go.mod is already tidied
        run: go mod tidy && git diff --no-patch --exit-code
      - name: Ensure code is properly formatted using gofumpt
        run: test -z "$(gofumpt -s -d .)"
      - name: Run linters
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          # renovate: depName=golangci/golangci-lint datasource=github-releases
          version: v1.50.1
          skip-go-installation: true
          args: --timeout=3m0s

      - name: Run tests
        env:
          RICHGO_FORCE_COLOR: "1"
          PVMIG_TEST_EXTRA_KUBECONFIG: /home/runner/.kube/kind-2.yaml
        run: richgo test -race -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic -timeout 20m -v ./...
      - name: Send coverage
        uses: codecov/codecov-action@v3.1.1
        with:
          files: coverage.txt


      - name: Build with Goreleaser
        if: ${{ always() }}
        uses: goreleaser/goreleaser-action@v3.2.0
        with:
          # renovate: depName=goreleaser/goreleaser datasource=github-releases
          version: v1.13.1
          args: build --snapshot --rm-dist --single-target
